RIP-Comm/sossoldi

- lib/Pages/home_page.dart
- lib/Pages/movements_page.dart
- lib/Pages/planning_budget_page.dart
- lib/Pages/settings_page.dart
- lib/Pages/statistics_page.dart
- lib/main.dart
- lib/widgets/CustomAppBar.dart
- lib/widgets/actionBar.dart
Added the blueprints for the different views of the app.
Added navigation system via actionBar widget.
Added custom appBar widget.
> Put down starting point for the app.

- lib/Pages/home_page.dart
- lib/Pages/planning_budget_page.dart
- lib/Pages/structure.dart
Started (to be improved):
- Implemented sections: budget, planned payments, graphs
To-do:
- dynamic data from DB
- set right icons
- dynamic colors for every budget
> Design: First version of the Planning page

- .github/workflows/flutter-ci.yml
- lib/model/recurring_transaction.dart
- test/model/recurring_transaction_test.dart
Signed-off-by: FedericoBruzzone <federico.bruzzone.i@gmail.com>
> Up: `recurring-transaction` \w `recurrence` filed

- lib/custom_widgets/alert_dialog.dart
To show a dialog, you can either use these straightforward functions to simply show some text with an "OK" button to dismiss it:
- void showInfoDialog(BuildContext context, String text)
- void showSuccessDialog(BuildContext context, String text)
- void showWarningDialog(BuildContext context, String text)
- void showErrorDialog(BuildContext context, String text)
or instantiate an AlertDialogBuilder, with different parameters, and then invoke show(). I added a comment on each property (lines 18-52), let me know should you have any question
> #44 Added alert dialog class

- lib/constants/style.dart
- lib/custom_widgets/account_modal.dart
- lib/custom_widgets/accounts_sum.dart
- lib/main.dart
- lib/pages/home_page.dart
- lib/pages/structure.dart
- test/widget/accounts_sum_test.dart
. Resolved issue #51 
. Implemented the layout and colors from the figma in the dashboard page
. Changed to relative path when needed
> Issue #51 + Dashboard layout

- lib/database/sossoldi_database.dart
- lib/model/bank_account.dart
- test/model/bank_account_test.dart
Just added mainAccount field in BankAccount table. Adjusted tests too.
> mainAccount field in BankAccount table

- lib/pages/settings_page.dart
Hi, I'm adding the settings page as defined in the Figma, but with the changed Appbar.
> add settings page

- lib/custom_widgets/line_chart.dart
- lib/pages/home_page.dart
- lib/pages/statistics_page.dart
- test/widget/line_chart_test.dart
Fixed a couple of issue with the linechart class and created the line chart at the top of the "Graphs" page.
> Created line chart for the graphs page

- lib/constants/functions.dart
- lib/custom_widgets/account_modal.dart
- lib/custom_widgets/accounts_sum.dart
- lib/custom_widgets/budget_circular_indicator.dart
- lib/custom_widgets/transactions_list.dart
- lib/model/bank_account.dart
- lib/model/recurring_transaction.dart
- lib/model/transaction.dart
- lib/pages/add_page/add_page.dart
- lib/pages/add_page/widgets/account_selector.dart
- lib/pages/add_page/widgets/category_selector.dart
- lib/pages/add_page/widgets/details_tile.dart
- lib/pages/add_page/widgets/recurrence_selector.dart
- lib/pages/home_page.dart
- lib/pages/settings_page.dart
- lib/providers/accounts_provider.dart
- lib/providers/transactions_provider.dart
- lib/routes.dart
- test/widget/accounts_sum_test.dart
- The add transactions page is now working fine, transfer and recurring transactions work in progress (waiting the new database scheme implementation).
- Graphic correction to the settings page.
- New dynamic standalone widget for transaction list.
> Add Transactions page + bug Fix

- lib/custom_widgets/accounts_sum.dart
- lib/custom_widgets/transactions_list.dart
- lib/database/sossoldi_database.dart
- lib/model/bank_account.dart
- lib/model/transaction.dart
- lib/pages/home_page.dart
Resolved some error with the new db fields.
Removed boolean type as it doesn't exist in the sqlite plugin: `bool is not a supported SQLite type. Use INTEGER and 0 and 1 values.` ([source](https://pub.dev/packages/sqflite#supported-sqlite-types))
> DB correction + minor graphic fix

- lib/constants/functions.dart
- lib/custom_widgets/transactions_list.dart
- lib/database/sossoldi_database.dart
- lib/model/bank_account.dart
- lib/model/budget.dart
- lib/model/currency.dart
- lib/model/recurring_transaction_amount.dart
- lib/model/transaction.dart
- lib/pages/add_page/add_page.dart
- lib/pages/add_page/widgets/account_selector.dart
- lib/pages/add_page/widgets/category_selector.dart
- lib/providers/transactions_provider.dart
- lib/routes.dart
- test/model/bank_account_test.dart
- test/model/budget_test.dart
- test/model/currency_test.dart
- test/model/transaction_test.dart
Now transactions works fine, insert/update/delete and income/expense/transfer.
The only missing implementation is for recurring payment.
Known Issue: A glitch when disposing the transaction modal on delete
> Transactions working implementation + minor fix

- lib/custom_widgets/accounts_sum.dart
- lib/custom_widgets/default_container.dart
- lib/database/sossoldi_database.dart
- lib/model/bank_account.dart
- lib/pages/accounts/account_list.dart
- lib/pages/add_page/widgets/account_selector.dart
- lib/pages/categories/category_list.dart
- lib/pages/more_info_page/collaborators_page.dart
- lib/pages/more_info_page/more_info.dart
- lib/pages/more_info_page/privacy_policy.dart
- lib/pages/settings_page.dart
- lib/pages/transactions_page/widgets/categories_pie_chart.dart
- lib/pages/transactions_page/widgets/categories_tab.dart
- lib/pages/transactions_page/widgets/list_tab.dart
- lib/providers/accounts_provider.dart
- lib/routes.dart
- test/model/bank_account_test.dart
- test/widget/accounts_sum_test.dart
- added "active" field in bankAccount Table
- Edited query to select all (active) bank Accounts
- Edited behavior of "Delete account" button, now just sets the account as inactive
- Fixed text overflow in settings page as per #96
- Imports cleanup, and general improvements
Delete your databases before testing.
> "active" field in bankAccount

- lib/pages/accounts/add_account.dart
- lib/providers/accounts_provider.dart
I added a numeric field for the `startingValue` field in the account creation page, this will close #106.
It's my first time working with flutter, so tell me anything wrong 😅
> Starting balance field in account creation page

- lib/pages/transactions_page/widgets/categories_tab.dart
Refactor some code and add some nullability checks
This PR fixes https://github.com/RIP-Comm/sossoldi/issues/99
> Refactor some code and add some nullability checks

- .github/workflows/flutter-ci.yml
- .gitignore
- analysis_options.yaml
- android/build.gradle
- ios/Flutter/Debug.xcconfig
- ios/Flutter/Release.xcconfig
- ios/Podfile
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- ios/Runner.xcworkspace/contents.xcworkspacedata
- ios/RunnerTests/RunnerTests.swift
- linux/CMakeLists.txt
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/Flutter-Debug.xcconfig
- macos/Flutter/Flutter-Release.xcconfig
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- macos/Runner.xcodeproj/project.pbxproj
- macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- macos/Runner.xcworkspace/contents.xcworkspacedata
- macos/Runner/Configs/AppInfo.xcconfig
- macos/Runner/MainFlutterWindow.swift
- macos/RunnerTests/RunnerTests.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
This PR aims to fix various build issues that I encountered during development.
What has been done:
- added various files to respect what .gitignore says, in order to not have 20+ uncommitted files, whenever a build is triggered
- updated flutter to latest stable version
> Update Flutter and fix platform projects

- .github/workflows/flutter-ci.yml
- .github/workflows/test.yml
- lib/database/sossoldi_database.dart
- test/model/bank_account_test.dart
- test/model/transaction_test.dart
> fix tests v2

- lib/pages/add_page/widgets/account_selector.dart
- lib/pages/add_page/widgets/category_selector.dart
Fix issue #147 adding a GestureDetector to handle on tap event.
> fix on tap more frequent catogories/accounts

- lib/constants/constants.dart
- lib/constants/style.dart
- lib/custom_widgets/account_modal.dart
- lib/custom_widgets/line_chart.dart
- lib/custom_widgets/transaction_type_button.dart
- lib/model/transaction.dart
- lib/pages/account_page/account_page.dart
- lib/pages/home_page.dart
- lib/pages/statistics_page.dart
- lib/pages/transactions_page/widgets/accounts_tab.dart
- lib/pages/transactions_page/widgets/categories_tab.dart
- lib/utils/app_theme.dart
- test/widget/line_chart_test.dart
- Graphs page now have the correct design and layout with working data for liquidity and account
- categories actually not working (todo)
- moved transaction_type_button to reuse it inside categories tab
- removed unused/incorrect color in categories
- some standard data liek colors on line chart now are default and no more required + semplified variable name
> Graphs Page Design Correction

- lib/pages/more_info_page/privacy_policy.dart
I updated the Privacy Policy section to something that should reflect more what we are currently doing. Also it should be enough to pass the review from the stores once we submit the apps.
@mikev-cw and @lucaantonelli I need confirmation that we do not currently gather any type of informations from our users like analytics or stuff like that.
> Update Privacy Policy

- lib/pages/more_info_page/collaborators_page.dart
> fix deprecated textstyles in collaborators page

- lib/pages/settings_page.dart
For the beta it will be useful to gather some feedback from the users so I prepared a google form. In the app I'm using feedback.sossoldi.com because it is a redirect and it can be changed in the future if we decide to create a new form or build one by ourselves
> Adding "Leave a feedback" option in settings

- lib/pages/add_page/add_page.dart
Fixing https://github.com/RIP-Comm/sossoldi/issues/185
> Handle transaction lower than 1

- lib/pages/planning_page/widget/budget_category_selector.dart
Fixing https://github.com/RIP-Comm/sossoldi/issues/186
> changed event to trigger modifyBudget + force number keyboard

- lib/custom_widgets/accounts_sum.dart
- lib/custom_widgets/rounded_icon.dart
- lib/custom_widgets/transactions_list.dart
- lib/pages/accounts/account_list.dart
- lib/pages/accounts/add_account.dart
- lib/pages/add_page/widgets/account_selector.dart
- lib/pages/add_page/widgets/amount_section.dart
- lib/pages/add_page/widgets/category_selector.dart
- lib/pages/add_page/widgets/details_list_disabled_tile.dart
- lib/pages/add_page/widgets/details_list_tile.dart
- lib/pages/add_page/widgets/label_list_tile.dart
- lib/pages/add_page/widgets/recurrence_list_tile.dart
- lib/pages/categories/add_category.dart
- lib/pages/categories/category_list.dart
- lib/pages/graphs_page/widgets/categories/categories_pie_chart2.dart
- lib/pages/graphs_page/widgets/linear_progress_bar.dart
- lib/pages/home_page.dart
- lib/pages/planning_page/planning_page.dart
- lib/pages/planning_page/widget/budget_card.dart
- lib/pages/planning_page/widget/recurring_payment_card.dart
- lib/pages/transactions_page/widgets/account_list_tile.dart
- lib/pages/transactions_page/widgets/accounts_pie_chart.dart
- lib/pages/transactions_page/widgets/categories_pie_chart.dart
- lib/pages/transactions_page/widgets/category_list_tile.dart
This PR fixes current issues:
- Fix #211 (just added spacing)
- Fix #215 (just added spacing)
- Fix #217 (made the switch adaptive to platform)
- I also implemented a new custom widget called RoundeIcon, since we use a lot this type of icons across the app, i made it resuable, so we also have less code in every widget that uses that component
> Fix #211 - #215 - #217 + New custom widget: RoundedIcon

- lib/constants/functions.dart
- lib/custom_widgets/transactions_list.dart
- lib/pages/add_page/add_page.dart
- lib/pages/add_page/widgets/amount_section.dart
- lib/pages/add_page/widgets/amount_widget.dart
- lib/pages/graphs_page/graphs_page.dart
- lib/providers/categories_provider.dart
- Fix #193 invalidate provider after creating category to refresh the list
- Fix #223 added validation to add transactions
- Fix colors of account selection buttons in dark mode for transfer transactions
> Fix #193 + Fix #223 + Fix transfer buttons in dark mode

- lib/pages/add_page/widgets/amount_section.dart
- Added Source/Destination Account icon/color while selecting data
- Closes https://github.com/RIP-Comm/sossoldi/issues/245
> fix: Update transfer page UI

- android/app/src/main/AndroidManifest.xml
- android/gradle.properties
- lib/custom_widgets/transactions_list.dart
- lib/pages/accounts/add_account.dart
- lib/pages/add_page/widgets/label_list_tile.dart
- lib/pages/categories/add_category.dart
- lib/utils/app_theme.dart
- lib/utils/notifications_service.dart
- Add an uncommited file to make it work notifications correctly on android
- Wrap the listtile added in the last PR with a Material widget, to make the ripple effect on click work again
- Fix balance issue pointed out by @mikev-cw in the last PR for demo data
- Removed unnecessary android permissions for import/export
> Graphic fix + Android setup fix

- docs/doc-guide.md
> docs: update doc-guide.md

- docs/privacy-policy.md
Fixes a small grammatical error
> Fix grammatical error

- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- Update the pubspec.lock file  to reflect correctly pubspec.yaml
- Update with correct dependencies for macos generated file
> fix(pubspec): lock file update + generated macos file

- lib/custom_widgets/transactions_list.dart
- lib/database/migrations/0002_account_net_worth.dart
- lib/database/migrations/migration_registry.dart
- lib/database/sossoldi_database.dart
- lib/model/bank_account.dart
- lib/model/transaction.dart
- lib/pages/accounts/add_account.dart
- lib/pages/transactions_page/widgets/list_tab.dart
- lib/providers/accounts_provider.dart
- lib/providers/transactions_provider.dart
- test/model/bank_account_test.dart
- test/widget/accounts_sum_test.dart
- Implement migration for countNetWorth in account table.
- Fix main account still visible as default in new transaction after deleting it
- Fix minor layout problem with container in transactions list.
Closes: #296 , #312 
About the layout problem, this is the before/after with extra space on top of the container wrongly added.
| Before | After |
|--------|-------|
| ![photo_2025-03-23_16-37-17](https://github.com/user-attachments/assets/dca8af41-f413-433a-b818-12be440f32c2) | ![photo_2025-03-23_16-37-19](https://github.com/user-attachments/assets/c8d88ffa-5368-4d92-b8ec-7bb8ea4e293e) |
- Tested on:
> Fix: CountNetWorth and Main Account removal correct handling

- lib/routes.dart
This pull request includes a change to the `makeRoute` function in the `lib/routes.dart` file to improve type safety when handling route arguments.
* [`lib/routes.dart`](diffhunk://#diff-db86e4d234b8ce36f13aae12c233aec35d10552b4b295edf1a456ae87fb16bbbL37-R42): Modified the `makeRoute` function to ensure the `args` variable is correctly typed as `Map<String, bool>?` by adding a type check and conditional assignment.
Closes: #365 
1. Do this
2. Do that
- Tested on:
Add any other information that we might know
> Fix potential crash in `/add-page` route handling

- lib/database/migrations/0001_initial_schema.dart
- lib/database/migrations/0002_account_net_worth.dart
- lib/database/sossoldi_database.dart
- lib/model/recurring_transaction.dart
- lib/pages/add_page/add_page.dart
- lib/pages/backup_page/backup_page.dart
- lib/pages/notifications/notifications_settings.dart
- lib/pages/planning_page/widget/older_recurring_payments.dart
- lib/pages/settings_page.dart
- lib/utils/csv_file_picker.dart
- test/sqflite/sqflite_ffi_test_for_dart.dart
- test/sqflite/sqflite_ffi_test_for_flutter.dart
- test/sqflite/sqflite_ffi_test_for_widget.dart
This commit solves:
- avoid_print
- BuildContext across async gaps
- 'rethrow' to rethrow a caught exception
> Fix analysis warning

- lib/pages/more_info_page/more_info.dart
- pubspec.yaml
> bump version

- android/app/build.gradle.kts
- android/app/setVersionCodeFDroid.gradle
- lib/model/bank_account.dart
- lib/pages/account_page/account_page.dart
- lib/providers/accounts_provider.dart
Gradle edits to handle FDroid and Play builds.
Build for Play store: 
`flutter build apk --flavor fdroid --split-per-abi`
Build for F-Droid:
`
flutter build apk --flavor fdroid --split-per-abi --flavor fdroid`
> Added Gradle FDroid flavor

- android/app/build.gradle.kts
- android/app/setVersionCodeFDroid.gradle
Changes needed for F-Droid release. Warn: This will probably break the CI
> Add release signing configuration and load keystore properties

- android/app/build.gradle.kts
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/ripster/sossoldi/MainActivity.kt
- ios/Runner/Info.plist
- lib/main.dart
- lib/pages/settings/general/general_settings_page.dart
- lib/providers/required_authentication_provider.dart
- macos/Flutter/GeneratedPluginRegistrant.swift
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
Added support for local device authentication, by default this option defaults to false.
This closes #248
> feat: allow user to enable local device authentication

- lib/pages/planning/manage_budget_page.dart
- lib/pages/planning/widget/budget_category_selector.dart
- lib/ui/theme/app_theme.dart
Closes: #459
Closes: #461 
- Added the ability to disable a button by adding status control to the theme.
- Modified the budget planning categories: categories already in use are now disabled in the selector, preventing duplicate assignments and ensuring valid planning.
- Added the correct currency chosen by the user
1. Try to add a new budget category: only unused categories should be selectable, and the "Add category budget" button is disabled if all categories are used.
2. In the budget list, try to change the category of an existing budget: categories already assigned to other budgets are disabled in the dropdown, except for the current one.
| …
> fix: update budget management functionality by adding category usage tracking
