lib/main.dart
lib/pages/add_page.dart
lib/pages/structure.dart
lib/routes.dart

Implemented a routing management system and added named routes.
Example for using it:
You want to navigate to '/settings' > `Navigator.of(context).pushNamed('/settings');`
Adding a new route inside routes.dart:
```
case '/example':
return _materialPageRoute(settings.name, ExamplePage());
```
There is 3 different types of page route animation:
- _cupertinoPageRoute
- _materialPageRoute
- _noTransitionPageRoute

Routing management

---

lib/database/sossoldi_database.dart
lib/model/recurring_transaction_amount.dart
test/model/recurring_transaction_amount_test.dart

Renamed `idRecurringTransaction` field to `idTransaction` (following recent db scheme changes).

Rename field in recurringTransactionAmount

---

lib/database/sossoldi_database.dart
lib/pages/settings_page.dart

I've improved our demo data set. Now when you launch application for the first time, a database with basic tables setup will be created, but all tables will be empty.
If you want to fill some demo data, head to settings: on the bottom i've added 2 options:
- "Clear DB" which will truncate all tables (useful when you play badly with the app, and need to "reset" to an empty state)
- "Clear and fill demo data" will truncate all tables as well, and fill they with demo data.
~~Every time you play with these 2 options, you need to force quit app to see results. Not sure why.~~
Known issues:
Filling transaction table has raised this error in dashboard transaction list:

Improved Demo data

---

lib/pages/transactions_page/transactions_page.dart
lib/pages/transactions_page/widgets/categories_pie_chart.dart
lib/pages/transactions_page/widgets/categories_tab.dart
lib/pages/transactions_page/widgets/category_list_tile.dart
lib/pages/transactions_page/widgets/list_tab.dart
lib/pages/transactions_page/widgets/transaction_list_tile.dart

I improved the List and Categories tabs. Here are two screenshots of how they look now.
<p float="left">
</p>
Currently, all transactions are queried from the database regardless of their date. We should query _only the ones in the selected time frame_. Also, the totals for the day and for each category are calculated in the build method of the widgets, which is not ideal. It might be better to retrieve them directly from the database with a designated query. The same goes for the groupings of transactions in their categories in the "Categories" tab.
The list of expandable categories in the "Categories" tab is wrapped in a `Sizebox` whose size is calculated every time a category is expanded. While a category gets collapsed, a `RenderFlex overflowed` is sometimes thrown, because the new …

Improvements to "Transactions" page

---

lib/pages/transactions_page/transactions_page.dart
lib/pages/transactions_page/widgets/custom_sliver_delegate.dart
lib/pages/transactions_page/widgets/list_tab.dart
lib/pages/transactions_page/widgets/month_selector.dart
lib/utils/date_helper.dart
lib/utils/formatted_date_range.dart

Fix #97 not visible text in Calendar view 
Date range is correctly displayed when the header is collapsed. Previously, it was hard-coded to "September 2022".
Start and end dates are now stored inside `transactions_page.dart`. This way they will be accessible by all tabs to be used for queries to the database.
Created `utils` folder for extension methods and utils functions.

Improved collapsible header on Transactions page

---

lib/pages/transactions_page/widgets/categories_tab.dart

[categories tab] Subcategories has overflowed text when opened/closed (#103) fixed

Overflow fixed in the transaction section

---

lib/pages/transactions_page/widgets/account_list_tile.dart
lib/pages/transactions_page/widgets/accounts_pie_chart.dart
lib/pages/transactions_page/widgets/accounts_tab.dart
lib/pages/transactions_page/widgets/categories_tab.dart

I've implemented and fixed the 'Transactions' page, particularly the 'Categories' and 'Accounts' tabs.
Categories:
- Adjusted the color scheme for both the list and the graph (fixed in #103 '[Categories Tab] Graph should take colors by category').
- Fixed the list (space between items and borderRadius).
Accounts:
- Implemented the page according to the Figma design.
- Enabled backend graph functionality with accounts.
- Enabled backend list functionality with accounts and transactions.
TODO:
- (As in the categories tab) 'Income' and 'Expenses' filters do not change the view."
https://github.com/RIP-Comm/sossoldi/assets/39710037/e86a1790-1fb5-4961-870c-14c64c25b2e7

Transaction section

---

lib/pages/general_options/general_settings.dart

See issue #137 
* Fixed typo in function name (`sellectCurrency()`)
* Added `BouncingScrollPhysics()` to `selectCurrency()`

Fixed not scrollable currency menu

---

lib/custom_widgets/account_modal.dart
lib/custom_widgets/accounts_sum.dart
lib/custom_widgets/budget_circular_indicator.dart
lib/custom_widgets/transactions_list.dart
lib/model/currency.dart
lib/pages/accounts/add_account.dart
lib/pages/add_page/widgets/amount_section.dart
lib/pages/general_options/general_settings.dart
lib/pages/general_options/widgets/currency_selector.dart
lib/pages/home_page.dart
lib/pages/planning_page/widget/budget_card.dart
lib/pages/planning_page/widget/budget_pie_chart.dart
lib/pages/statistics_page.dart
lib/pages/transactions_page/widgets/account_list_tile.dart
lib/pages/transactions_page/widgets/accounts_pie_chart.dart
lib/pages/transactions_page/widgets/categories_pie_chart.dart
lib/pages/transactions_page/widgets/category_list_tile.dart
lib/pages/transactions_page/widgets/custom_sliver_delegate.dart
lib/pages/transactions_page/widgets/month_selector.dart
lib/providers/currency_provider.dart
test/widget/accounts_sum_test.dart

I managed the currency selection. 
I created a basic provider.
Then, obtaining the value through it, I display the selected currency within the application. 
Additionally, some StatelessWidget have been converted to ConsumerWidget just to read the selected currency value. 
Feel free to provide any suggestions or requests for modifications!

CurrencySelector #70

---

lib/model/transaction.dart

Addressing issue #151.
I just added quotes around `'$transactionTable'` since `transaction` is a reserved keyword in SQL.

Fixed SelectById() old query

---

README.md
lib/pages/add_page/add_page.dart
lib/pages/add_page/widgets/details_list_tile.dart
lib/pages/add_page/widgets/label_list_tile.dart

- Added contributing link to the general README
- Added minus sign on an expense while editing in the Add Page
- Changed color of values in Add Page
- Adds hint text for description
It was added in the designs [here](https://www.figma.com/file/6NyY9yqunpbU7HIkbNEAL3/Sossoldi-App?type=design&node-id=0-1&mode=design&t=cbf7CsGaOA27mQqg-0)
<details>
<summary>Screenshots & Recordings</summary>
</details>

Add Page improvements + minor README addition

---

lib/main.dart
lib/pages/notifications/notifications_service.dart
lib/pages/notifications/notifications_settings.dart
lib/pages/notifications/widgets/NotificationTypeTile.dart
lib/pages/settings_page.dart
lib/providers/settings_provider.dart
lib/utils/worker_manager.dart
pubspec.yaml

Hi,
I have submitted a pull request, but it is not yet 100% complete, and I am seeking your guidance.
I've tested notifications on the emulator, and it works correctly. However, when building the app in release mode, I get the error "Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.0, expected version is 1.5.1.".
If you have any insights or suggestions on how to address this Kotlin version compatibility issue, it would be very appreciated.
Additionally, for context,  I'm using the WorkerManager library to schedule notifications (it may be useful for scheduling recurring transactions as well).

WIP notifications system

---

lib/pages/transactions_page/widgets/account_list_tile.dart
lib/pages/transactions_page/widgets/accounts_tab.dart
lib/pages/transactions_page/widgets/categories_tab.dart
lib/pages/transactions_page/widgets/category_list_tile.dart

The Categories and Accounts page in Transactions now show correctly the category and account name of each transaction instead of their ids.

Fix: text instead of ids in transactions page

---

lib/pages/accounts/add_account.dart

**Summary:**
Refactored the `AddAccount` screen layout to resolve scrolling issues.
**Changes:**
- Replaced `Stack` with `Column` to streamline vertical arrangement.
- Wrapped the `SingleChildScrollView` component with `Expanded`.
- Ensured the confirmation button remains visible and does not overlap with scrollable content.
- Enhanced user experience by making sure the input fields and options are fully accessible without obstruction.
**Screenshots:**
After attempt to scroll.
- **Before:**
- **After:**

Fix: AddAccount layout scrolling issue

---

android/app/build.gradle
android/build.gradle
android/settings.gradle

This pull request addresses deprecation warnings related to the use of Flutter's Gradle plugins. Specifically, it updates the Gradle configuration files to replace the imperative `apply` script method with the declarative `plugins` block.
When running `flutter run`, the following deprecation warnings were encountered:
```
Launching lib/main.dart on CPH2211 in debug mode...
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply
You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a …
```

Update Flutter Gradle plugin configuration

---

lib/model/bank_account.dart

This pull request addresses a bug where active bank accounts with only recurring transactions were being excluded from the query results.
- Corrected the SQL query to ensure that active bank accounts with only recurring transactions are no longer excluded from the results.
- Added a new `recurringFilter` variable to clearly define and encapsulate the logic for filtering out non-recurring transactions.
- Adjusted the `LEFT JOIN` clause to apply the recurring filter within the `ON` condition, preserving all active accounts while accurately calculating their balances.
- This fix resolves an issue where certain accounts disappeared from the query results, ensuring all active accounts are correctly handled in the balance calculation.
This video demonstrates the issue that this pull request …

Fix for Account Exclusion Issue Due to Recurring Transactions

---

lib/pages/categories/add_category.dart
lib/pages/settings_page.dart

This aims to address Issues #178 and #176
To toggle the dev bar, you need to tap 4 times the word "Settings" on top of the settings page

Hide dev bar and subcat button

---

lib/pages/graphs_page/widgets/categories/categories_card.dart

Workaround to fix #180.
Main issue is caused by `CategoriesCard` getting resized when its state changes, which falls into flutter/flutter#99158.
Solved partially by creating a widget with the same height as the previous one.

Fix: 180 - unpleasant scroll-to-the-top on graph page

---

lib/pages/categories/add_category.dart
lib/pages/onboarding_page/widgets/budget_setup.dart
lib/pages/planning_page/manage_budget_page.dart
lib/providers/categories_provider.dart

Currently a user could create an income category and then add a budget to it. This PR aims at resolving this by doing the following things:
1. During the Onboarding phase the user can only create Expense categories and add a budget to them
2. In the planning page when I user wants to create a new budget only the Expense categories are shown

Bug fix: Prevent user to create budgets for income categories

---

lib/pages/add_page/add_page.dart
lib/providers/accounts_provider.dart

Currently The account is not updated after changes in transations.
This PR will:
- Add an updateAccount method inside the add_page view
- Add call to updateAccount when creating or updating transaction
- Add call to updateAccount when removing transaction
Closes #187 
https://github.com/user-attachments/assets/312b3a55-5564-4f98-bd0f-ec150bfd5880

Bug fix/187: update account after updating transaction

---

.gitignore
devtools_options.yaml
ios/Podfile
ios/Podfile.lock
ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
ios/Runner/AppDelegate.swift
lib/routes.dart
pubspec.lock

This PR address the issue of the routing system for the **Settings Page.**
Before this PR the Settings Page was not considered as a route, instead all the content of the page was replacing the content below, since the `_notTransitionPageRoute()` method was used to "push" the route.
After this commit to push the route the `_cupertinoPageRoute()` method is being used. With that edit the Settings Page is treated like a normal route, and so it's possible to swipe back and navigate correctly to the route.
---
Closes: #218

fix(routing): iOS swipe back on settings page

---

lib/custom_widgets/line_chart.dart
lib/model/budget.dart
lib/pages/graphs_page/graphs_page.dart
lib/pages/home_widget/budgets_home.dart
lib/pages/planning_page/manage_budget_page.dart
lib/providers/budgets_provider.dart

Fixing the following issues:
- #220: Fixed the issue with the weird display of the line graph by lowering the curve smoothness. This makes the graph a bit more pointy but it should be more accurate
- #213: Before a budget was displayed only if at least a transaction was added for the current month, now they are always displayed
- On the graphs page the line graph wasn't displaying the months but the current month days. Now it is fixed by specifying Period.year (Untracked)
- When no budget is added we had an empty section, now I added a simple text
```SEE SECTION ABOVE```
1. Add a big income transaction
2. Add a small expense for the day after
3. You shouldn't see a big curve as before
1. Add a budget for a category that has no transaction this month
2. Check that in the dashboard the …

Fix #220 & #213 + Untracked bugs

---

lib/custom_widgets/transactions_list.dart
lib/model/bank_account.dart
lib/pages/account_page/account_page.dart
lib/pages/accounts/add_account.dart
lib/pages/transactions_page/widgets/account_list_tile.dart
lib/providers/accounts_provider.dart
lib/providers/transactions_provider.dart

This PR aims to add the possibility to change the total amount of your bank account. 
Steps to take a reconciliation:
- Go to Settings Page
- Go to Accounts
- Just change the total amount and click "Update Balance"
By doing those steps, the total amount of your accounts updated and a new transaction "Reconciliation" is being created.
This PR also improve the `transaction_list.dart` code by using `ListView.separated`and `ListTile` to stick to material widget.
-Closes #197

feat(account, transaction): reconciliation and transaction list

---

lib/pages/add_page/widgets/amount_widget.dart
lib/pages/more_info_page/collaborators_page.dart
test/widget/amount_widget_test.dart

In this PR:
- b8f59020541a7499bfedf915b0c5a881b18101e3: 
- Updated `keyboardType` to have the `signed` property `true` only when running on Android. This allows to show the numpad on iOS as well.
- Added a new `FilteringTextInputFormatter` which allows for one period only to be entered in the `TextField`.
- 58b1501575e4fb02d9854720567273636870542a: Added two tests for the `AmountWidget` widget to check that only single period are allowed in the `TextField`.
Resolve #219

Resolve #219: Add input formatter to allow one period, changes to keyboardType to show numpad on iOS

---

lib/pages/add_page/add_page.dart
lib/utils/app_theme.dart

In this PR:
- Added `cupertinoOverrideTheme` for the `AppTheme`
- Updated the background color of the `CupertinoDatePicker`'s `Container` to [secondarySystemBackground](https://api.flutter.dev/flutter/cupertino/CupertinoColors/secondarySystemBackground-constant.html), so that it has contrast in dark mode.
Resolve #249, #264 (duplicate)

fix: Resolve #249, #264 - Updated CupertinoDatePicker background color

---

lib/custom_widgets/native_alert_dialog.dart
lib/pages/accounts/add_account.dart
lib/pages/accounts/widgets/confirm_account_deletion_dialog.dart
lib/utils/app_theme.dart
test/widget/native_alert_dialog_widget_test.dart

In this PR:
- Added a new widget, `AdaptiveDialog`:
This was done for having a convenient way of displaying a native looking dialog. The problem with `AlertDialog.adaptive` is that you still need to differentiate the actions, otherwise you'll end up with Material buttons on the Cupertino widgets. To simplify this process I've create a convenience class for the actions, which will be mapped to the correct platform widget (`TextButton` on Android, `CupertinoDialogAction` on iOS).
- Added the confirmation dialog:
When tapping on the _Delete account_ button you'll now see a dialog which will ask you to confirm your choice. I don't know if the wording on the dialog can be improved, it looked good enough for me but I'm open to suggestions.
- After the account has been deleted, navigate back to …

feat: Resolve #200 - Added confirmation dialog when deleting an account

---

lib/custom_widgets/line_chart.dart

Small typo fix in `line_chart.dart`
We are sorry but there ~are~ **is** not\nenough data to make the graph...
more info: https://grammarist.com/usage/data/

fix: typo singular data

---

lib/pages/accounts/add_account.dart
lib/routes.dart
lib/utils/app_theme.dart

Copy of #301 
In this PR:
- Replaced `CupertinoSwitch` with `Switch.adaptive` in `lib/pages/accounts/add_account.dart`.
- Added `SwitchThemeData`:
- @federicopozzato probably worth to have a look at the colors, feel free to suggest changes. 
You can find more info on the [Material3 Switch guidance](https://m3.material.io/components/switch/overview).
- Created the `buildAdaptiveRoute` wrapper function for `_materialPageRoute` and `_cupertinoPageRoute` in `lib/routes.dart`. This ensure that a Material route is used on Android and a Cupertino route is used on iOS. 
It might give conflicts with #295 and #290.
|LightMode|DarkMode|
|-----------|-----------|
|![Screenshot_1742060920](https://github.com/user-attachments/assets/bd65bc80-781d-4b5c-a0b6-de9b3128071c)|![Screenshot_1742060907](https:// …

chore: Resolve #243 - Improve platform specific UI elements and route transitions

---

lib/main.dart
lib/pages/onboarding_page/widgets/account_setup.dart

This PR resolves issue #232, where users who performed an import process were required to redo the onboarding process. Additionally, I noticed that the handling of the `is_first_login` variable in the main function might be not ideal.  
The issue came from Phoenix, the library used to restart/reload the app after completing an import process. Phoenix re-executes the `build()` method of the `Launcher` widget, preventing the `_isFirstLogin` variable in `main.dart` from being properly reassigned. Its value was only retrieved inside the `main()` function, leading to incorrect behavior.  
While investigating, I also found another bug: when a user opens the app for the first time, the onboarding process is displayed. However, if they close the app while still in the onboarding flow, they will …

fix: 232 | Rework of 'is_first_login' variable

---

pubspec.yaml

Gap was not being used in the whole project and so it was an unnecessary dependency
Closes: #361
Removed `gap` from `pubspec.yml`
- Tested on:
Don't think that Android tests are needed here 😄

del(pubspec): remove gap as dependency

---

lib/pages/account_page/account_page.dart
lib/pages/accounts/add_account.dart
lib/pages/add_page/widgets/amount_widget.dart
lib/pages/onboarding_page/widgets/account_setup.dart
lib/pages/planning_page/widget/budget_category_selector.dart

The aim of this PR is to standardize the way numerical input fields are formatted.
I did a similar change a couple of weeks ago on the `lib\pages\add_page\widgets\amount_widget.dart` and I thought I could replicate this on every `TextField` widget where the `inputFormatters` property is used.
While doing this change I realized there is an **unused** custom input formatter in `lib\utils\decimal_text_input_formatter.dart` which does everything we need (introduced in the codebase more than 1 year ago).
Please let me know if this was not used for a specific reason. The test I wrote for my previous PR are still passing so I'm assuming everything is working as expected.
I haven't tested specifically on iOS but the logic that replaces the comma (which is present in the iOS numpad) with the …

fix: Resolve #381 - Use DecimalTextInputFormatter in TextFields

---

lib/utils/decimal_text_input_formatter.dart

Negative values were not handled correctly by the DecimalTextInputFormatter.
Closes: #416 
1. Do this
2. Do that
- Tested on:
Add any other information that we might know

fix: handle negative values correctly in DecimalTextInputFormatter

---

.github/workflows/ci-cd.yml
lib/pages/add_page/widgets/category_selector.dart

This pull request updates the category selection behavior by automatically closing the category panel after a user selects a category.
Currently, after selecting a category, the panel remains open, requiring the user to manually close it. This extra step interrupts the navigation flow and creates friction in the user experience.
Closes: #354  
1. Add a new transaction.
2. Click on a category from the "All categories" list.
3. The panel will now automatically close upon selecting a category.
- Tested on:
Add any other information that we might know

feat(ui): auto-close category panel on selection for improved UX

---

lib/pages/transactions_page/widgets/account_list_tile.dart
lib/pages/transactions_page/widgets/category_list_tile.dart

Expense values were not displayed correctly when grouping transactions by category or by account.
Closes: #427 
1. Do this
2. Do that
Here's the new behaviour:
This also matches the [figma design](https://www.figma.com/design/6NyY9yqunpbU7HIkbNEAL3/Sossoldi-App?node-id=1529-4389&t=Q9wenCXn4W9EJJRF-0)
- Tested on:
Sorry I messed up with the old PR

fix: correctly show expense amounts in list tiles

---

lib/pages/onboarding_page/widgets/category_button.dart

Removing overflow on setup page to **CategoryButton** widget

fix: removing overflow on category buttons

---

lib/pages/categories/add_category.dart

When creating a new category, the category type dropdown is preselected based on the transaction type (income or expense).  
Closes: #390  
1. Add a new category from the **Add Transaction** screen with **'income'** selected as the transaction type.  
2. The category type dropdown should default to **'income'**.  
3. Repeat steps 1 and 2 with **'expense'**, and the dropdown should default to **'expense'**.  
1. Open **Add Transaction** and select **'income'** as the transaction type.  
2. Go to **Settings → Categories → + (Add Category)**. The category type dropdown should default to **'income'**.  
3. Repeat steps 1 and 2 with **'expense'**, and the dropdown should default to **'expense'**.  
1. Open **Add Transaction** and select **'transfer'** as the transaction type.  
2. Go to …

perf(add_category): autoselect category type based on transaction type

---

lib/providers/transactions_provider.dart
lib/ui/widgets/transactions_list.dart

Closes: #440 
Transactions will not be assigned a category.
- Tested on:
I chose not to invalidate the category provider so that the user can still see the last selected category when switching back to an expense/income transaction.
These changes won't have any effect on the older transfers, and those displayed incorrectly will continue to appear in this manner.

fix: Transactions can have categories

---

lib/database/migrations/0001_initial_schema.dart
lib/database/migrations/0002_account_net_worth.dart
lib/database/migrations/0003_recurring_transaction_type.dart
lib/database/migrations/migration_registry.dart
lib/database/sossoldi_database.dart
lib/main.dart
lib/model/currency.dart
lib/model/recurring_transaction.dart
lib/model/transaction.dart
lib/pages/add_page/add_page.dart
lib/pages/add_page/widgets/amount_widget.dart
lib/pages/planning_page/widget/recurring_payment_card.dart
lib/providers/transactions_provider.dart
lib/ui/widgets/budget_circular_indicator.dart
test/model/recurring_transaction_test.dart

Recurring transactions were previously limited to Expenses.
This update allows recurring transactions to be used for Income and Transfers as well.
I noticed a problem, albeit non-blocking: the color of the selected transaction remains persistent even after the type change via the top button. This happens because the fallback value of the type is determined by the parameter passed to the function.
I chose not to intervene in this aspect because, given the current state management model, it would be necessary to rethink the assignment of the transaction type to the provider. The goal would be to ensure consistent management in line with the Single Source of Truth principle, avoiding duplication or inconsistent state.
#199

feat(transactions): enable recurring transactions for Income and Transfers

---

lib/pages/planning/widget/recurring_payments_list.dart
lib/pages/transactions/create_transaction/create_transaction_page.dart
lib/providers/transactions_provider.dart

when create button clicked in bottom nav bar floating action button
to add transaction( specifically recurring transaction ) when we add it its not reflecting immediately in transaction -> list screen and planning -> recurring payment section screen 
because the state is not updating correctly so with this changes now once we add recurring transaction via floating action button automatically the transaction should be updated in both screen without need of navigating back to diff screen and coming back to the screen to see the updated recurring transaction
Closes: #463 
1. Do this
2. Do that …

fixed state sync issue for transaction and recurring transaction page

---

lib/pages/transactions/widgets/account_list_tile.dart
lib/pages/transactions/widgets/category_list_tile.dart
lib/pages/transactions/widgets/month_selector.dart

Please provide a clear and concise description of what this pull request does.  
Explain why this change is necessary and what problem it solves.  
Closes: #456 & #457 
- Removed fixed height for the transaction tile
- Removed one of the currency symbols
1. Check the account and category lists of transactions and make sure that the last one is not cut
2. Check that in the month selector there is only one currency symbol
| Transaction tile  |    <img width="640" height="1222" alt="481005991-dd2bed54-3c8d-4991-b1be-5d52c4d65978" src="https://github.com/user-attachments/assets/fa388b63-b4fc-4127-8c06-13328b467d6a" />   |   <img width="640" …

Fix list tile height & currency symbol in month selector
